In [7]:
import numpy as np

def decmp_lu(x):
    if type(x) is not np.ndarray:
        raise TypeError()
    return elimination(x)

def elimination(x):
    shape_length=x.shape[1]
    inv_l=np.identity(x.shape[1])
    for i in range(0,shape_length-1):
        for j in range(i+1,shape_length):
            inv_l,x = calculation(square=inv_l,x=x,left_pointer=i,right_pointer=j)
    return inv_l,x

def calculation(square,x,left_pointer,right_pointer):
    l_coef = x[right_pointer][left_pointer]/x[left_pointer][left_pointer]
    x[right_pointer]=x[right_pointer]-l_coef*x[left_pointer]
    e_ji=np.identity(x.shape[1])
    e_ji[right_pointer][left_pointer]=-l_coef
    return np.dot(e_ji,square),x

In [8]:
def mask_zero(num):
     return 0 if abs(num)<1e-5 else num

In [9]:
np.random.seed(42)
A_decmp_test = 5*np.random.randn(5,5)
b_decmp_test = 25*np.random.randn(5,1)
print("Below is the input 5*5 matrix A of Gaussian distribution with mean=0 and sd=5: \r")
print(A_decmp_test)
vfunc_rnd = np.vectorize(lambda x: mask_zero(x))
print("\n")
print("Below is the inversed L after LU decomposistion:\r")
print(vfunc_rnd(decmp_lu(A_decmp_test)[0]))
print("\n")
print("Below is the U after LU decomposistion:\r")
print(vfunc_rnd(decmp_lu(A_decmp_test)[1]))
print("\n")
print("Below is the vector b on the right side of the equation:\r")
print(b_decmp_test)

Below is the input 5*5 matrix A of Gaussian distribution with mean=0 and sd=5: 
[[ 2.48357077 -0.69132151  3.23844269  7.61514928 -1.17076687]
 [-1.17068478  7.89606408  3.83717365 -2.34737193  2.71280022]
 [-2.31708846 -2.32864877  1.20981136 -9.56640122 -8.62458916]
 [-2.81143765 -5.0641556   1.57123666 -4.54012038 -7.06151851]
 [ 7.32824384 -1.1288815   0.33764102 -7.12374093 -2.72191362]]


Below is the inversed L after LU decomposistion:
[[ 1.          0.          0.          0.          0.        ]
 [ 0.47137162  1.          0.          0.          0.        ]
 [ 1.11812482  0.39280741  1.          0.          0.        ]
 [-0.15865311  0.191017   -1.47991094  1.          0.        ]
 [-1.92133913  1.27834411 -4.54408049  4.12207635  1.        ]]


Below is the U after LU decomposistion:
[[ 2.48357077 -0.69132151  3.23844269  7.61514928 -1.17076687]
 [ 0.          7.57019474  5.36368364  1.24219335  2.16093394]
 [ 0.          0.          6.33806478 -1.97377886 -8.86804463]
 [ 0. 